read_holdings:
  description: "reads holdings registers"
  fields: 
    unit: 
      description: "address of slave"
      example: 4      
    address:
      description: "start address 0 - 120"
      example: '0'
    hub:
      description: "name of hub can (optional)"
    count:
      description: "count of holdings to return"
      example: 100      
    timeoutms:
      description: "timeout in ms"
      example: 150
read_holding:
  description: "reads one holding register"
  fields: 
    unit: 
      description: "address of slave"
      example: 4      
    address:
      description: "start address 0 - 120"
      example: '0'
    hub:
      description: "name of hub can (optional)"            
write_holding:
  description: "write to holding register"
  fields: 
    unit: 
      description: "address of slave"
      example: 4      
    address:
      description: "start address 0 - 120"
      example: '0'
    hub:
      description: "name of hub can (optional)"            
    value:
      description: "value to be written to register"
      example: '1'
scan_unit:
  description: "scan structure of slave and generate yaml file. Response and file path is logged in logger"
  fields:
    slave:
      description: "address of slave"
      example: 4
    hub:
      description: "name of hub"
      example: "default"

