- id: '1666283701554'
  alias: purge db
  description: ''
  trigger:
  - platform: time
    at: 04:00:00
  condition: []
  action:
  - service: recorder.purge
    data:
      repack: true
  mode: single
