# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

system_log:
  max_entries: 1000

#logger:
#  default: info

homeassistant:
  time_zone: Europe/Prague
  customize:
    switch.switch_wc:
      friendly_name: "Vetrak wc"
    switch.switch_5_10_servo_open_floor_circle:
      friendly_name: "Servo podlahy otevírá"
    switch.switch_5_11_servo_close_floor_circle:
      friendly_name: "Servo podlahy zavírá"
    switch.switch_5_12_servo_open_radiator_circle:
      friendly_name: "Servo radiátorů otevírá"
    switch.switch_5_13_servo_close_radiator_circle:
      friendly_name: "Servo radiátorů zavírá"
    binary_sensor.binary_sensor_5_1_thermostat_negative:
      friendly_name: "Termostat kuchyň"
    switch.switch_5_7_pump_floor_circle:
      friendly_name: "Čerpadlo podlaha"
    switch.switch_5_8_pump_radiator_circle:
      friendly_name: "Čerpadlo radiátory"
    sensor.temp_floor_circle:
      friendly_name: "Teplota podlahový okruh"
    sensor.temp_radiator_circle:
      friendly_name: "Teplota radiátorový okruh"
    sensor.temp_tank_top:
      friendly_name: "Teplota nádrže horní"
    sensor.temp_tank_middle:
      friendly_name: "Teplota nádrže střed"
    sensor.temp_tank_bottom:
      friendly_name: "Teplota nádrže dolní"
    sensor.temp_boiler:
      friendly_name: "Teplota kotle"
    input_number.servo_time_floor_circle:
      friendly_name: "Čas otevření serva (s)"
    climate.climate_floor_circle:
      friendly_name: "PID regulátor podlahy"
    climate.climate_radiator_circle:
      friendly_name: "PID regulátor radiátorů"
    input_number.servo_time_radiator_circle:
      friendly_name: "Čas otevření serva (s)"
    binary_sensor.binary_sensor_5_2_waterheater_thermostat_negative:
      friendly_name: "Termostat boiler"
    switch.switch_5_9_pump_waterheater:
      friendly_name: "Čerpadlo boiler"
    switch.switch_5_15_servo_waterheater:
      friendly_name: "Servo boiler"
    switch.switch_5_14_waterheater_mode:
      friendly_name: "Ohřev TUV kotlem"
    input_number.min_temp_boiler_water_heater:
      friendly_name: "Minimální teplota kotle"
    input_number.min_temp_tank_water_heater:
      friendly_name: "Minimální teplota nádrže"

template:
  - sensor:
      - name: "floor_set_point"
        unit_of_measurement: "°C"
        state: "{{  state_attr('climate.climate_floor_circle','temperature') }}"
  - binary_sensor:
      - name: binary_sensor_5_2_waterheater_thermostat_negative
        state: "{{is_state('binary_sensor.binary_sensor_5_2_waterheater_thermostat', 'off')}}"
        device_class: heat
      - name: binary_sensor_5_1_thermostat_negative
        state: "{{is_state('binary_sensor.binary_sensor_5_1_thermostat', 'off')}}"

climate:
  - platform: smart_thermostat
    name: climate_floor_circle
    heater: input_number.servo_value_floor_circle
    target_sensor: sensor.temp_floor_circle
    min_temp: 15
    max_temp: 45
    ac_mode: False
    target_temp: 17
    keep_alive:
      seconds: 5
    initial_hvac_mode: "heat"
    away_temp: 16
    kp: 5
    ki: 3
    kd: 2
    pwm: 0
    difference: 100
    noiseband: 0.5
  - platform: smart_thermostat
    name: climate_radiator_circle
    heater: input_number.servo_value_radiator_circle
    target_sensor: sensor.temp_radiator_circle
    min_temp: 15
    max_temp: 60
    ac_mode: False
    target_temp: 40
    keep_alive:
      seconds: 5
    initial_hvac_mode: "heat"
    away_temp: 16
    kp: 5
    ki: 3
    kd: 2
    pwm: 0
    difference: 100
    noiseband: 0.5

input_select:
  pump_mode_floor_circle:
    name: Režim čerpadla
    options:
      - "On"
      - "Off"
      - Auto
  pump_mode_radiator_circle:
    name: "Režim čerpadla"
    options:
      - "On"
      - "Off"
      - Auto
  water_heater_mode:
    name: "Režim boileru"
    options:
      - Electric
      - Boiler
      - Auto

input_number:
  servo_value_floor_circle:
    name: "Otevření serva podlahy"
    initial: 0
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"
  servo_value_radiator_circle:
    name: "Otevření serva radiátorů"
    initial: 0
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"
  servo_time_radiator_circle:
    #name: "Radiator servo time"
    initial: 0
    min: -130
    max: 130
    step: 1
    mode: box
    unit_of_measurement: "s"
  servo_time_floor_circle:
    #name: Floor servo time
    initial: 0
    min: -130
    max: 130
    step: 1
    mode: box
    unit_of_measurement: "s"
  setpoint_floor_circle:
    #name: Set point circle floor
    initial: 30
    min: 20
    max: 100
    step: 0.2
    mode: box
    unit_of_measurement: "°C"
  setpoint_radiator_circle:
    #name: Set point circle radiator
    initial: 30
    min: 20
    max: 100
    step: 0.2
    mode: box
    unit_of_measurement: "°C"
  min_temp_boiler_pump_floor_circle:
    name: "Minimální teplota kotle"
    max: 100
    min: 0
    unit_of_measurement: "°C"
    mode: box
  min_temp_boiler_pump_radiator_circle:
    name: "Minimální teplota kotle"
    max: 100
    min: 0
    unit_of_measurement: "°C"
    mode: box
  min_temp_tank_pump_floor_circle:
    name: "Minimální teplota nádrže"
    max: 100
    min: 0
    unit_of_measurement: "°C"
    mode: box
  min_temp_tank_pump_radiator_circle:
    name: "Minimální teplota nádrže"
    max: 100
    min: 0
    unit_of_measurement: "°C"
    mode: box
  min_temp_tank_water_heater:
    #name: Minimalni teplota nadrze
    max: 100
    min: 0
    unit_of_measurement: "°C"
    mode: box
  min_temp_boiler_water_heater:
    #name: Minimalni teplota kotle
    max: 100
    min: 0
    unit_of_measurement: "°C"
    mode: box

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

modified_modbus:
  # - name: default2
  #   type: serial
  #   method: rtu
  #   port: /dev/ttyUSB0
  #   baudrate: 115200
  #   stopbits: 1
  #   bytesize: 8
  #   parity: N
  - name: default
    type: tcp
    port: 9234
    host: 192.168.89.78

binary_sensor 3:
  - holdings:
      - bit: 8
        hub: default
        name: binary_sensor_3_2
        offset: 28
        slave: 3
        value_off: 0
        value_on: 1
    platform: modified_modbus
sensor  3:
  - holdings:
      - count: 25
        holdings_type: string
        hub: default
        name: rfidreader_3
        offset: 95
        slave: 3
    platform: modified_modbus
switch 3:
  - holdings:
      - command_off: 3
        command_on: 259
        hub: default
        name: switch_3_0
        offset: 27
        slave: 3
        state_off: 3
        state_on: 259
    platform: modified_modbus
  - holdings:
      - command_off: 0
        command_on: 1
        hub: default
        name: rfidreader_reset_3
        offset: 94
        slave: 3
        state_off: 0
        state_on: 1
    platform: modified_modbus

binary_sensor 4:
  - holdings:
      - hub: default
        name: binary_sensor_4_1
        offset: 23
        slave: 4
        value_off: 513
        value_on: 769
        bit: 8
    platform: modified_modbus
  - holdings:
      - hub: default
        name: binary_sensor_bathroom #4.2
        offset: 24
        slave: 4
        value_off: 1538
        value_on: 1794
        bit: 8
    platform: modified_modbus
  - holdings:
      - hub: default
        name: binary_sensor_4_3
        offset: 25
        slave: 4
        value_off: 515
        value_on: 771
        bit: 8
    platform: modified_modbus
sensor  4:
  - holdings:
      - OwId: 28905d080600001b
        holdings_type: ds18b20
        device_class: temperature
        hub: default
        name: temp_bathroom
        slave: 4
        unit_of_measurement: "°C"
    platform: modified_modbus
switch 4:
  - holdings:
      - command_off: 4
        command_on: 260
        hub: default
        name: switch_bathroom
        offset: 26
        slave: 4
        state_off: 4
        state_on: 260
    platform: modified_modbus

binary_sensor 5:
  - holdings:
      - hub: default
        name: binary_sensor_5_1_thermostat
        offset: 23
        slave: 5
        value_off: 513
        value_on: 769
        bit: 8
    platform: modified_modbus
  - holdings:
      - hub: default
        name: binary_sensor_5_2_waterheater_thermostat
        offset: 24
        slave: 5
        value_off: 514
        value_on: 770
        bit: 8
    platform: modified_modbus
  - holdings:
      - hub: default
        name: binary_sensor_5_3
        offset: 25
        slave: 5
        value_off: 515
        value_on: 771
        bit: 8
    platform: modified_modbus
  - holdings:
      - hub: default
        name: binary_sensor_5_4
        offset: 26
        slave: 5
        value_off: 516
        value_on: 772
        bit: 8
    platform: modified_modbus
  - holdings:
      - hub: default
        name: binary_sensor_5_5
        offset: 27
        slave: 5
        value_off: 517
        value_on: 773
        bit: 8
    platform: modified_modbus
  - holdings:
      - hub: default
        name: binary_sensor_5_6
        offset: 28
        slave: 5
        value_off: 518
        value_on: 774
        bit: 8
    platform: modified_modbus

sensor  5:
  - holdings:
      - OwId: 28ff63ad64150155
        device_class: temperature
        holdings_type: ds18b20
        hub: default
        name: temp_radiator_circle
        slave: 5
        unit_of_measurement: "°C"
    platform: modified_modbus
  - holdings:
      - OwId: 28ffbdd06415019c
        device_class: temperature
        holdings_type: ds18b20
        hub: default
        name: temp_floor_circle
        slave: 5
        unit_of_measurement: "°C"
    platform: modified_modbus
  - holdings:
      - OwId: 28cf74b4010000e3
        device_class: temperature
        holdings_type: ds18b20
        hub: default
        name: temp_floor_livingrom
        slave: 5
        unit_of_measurement: "°C"
    platform: modified_modbus
  - holdings:
      - OwId: 282b29e5050000a6
        device_class: temperature
        holdings_type: ds18b20
        hub: default
        name: temp_tank_middle
        slave: 5
        unit_of_measurement: "°C"
    platform: modified_modbus
  - holdings:
      - OwId: 28ff88d2641501cd
        device_class: temperature
        holdings_type: ds18b20
        hub: default
        name: temp_tank_bottom
        slave: 5
        unit_of_measurement: "°C"
    platform: modified_modbus
  - holdings:
      - OwId: 28ff7dae64150103
        device_class: temperature
        holdings_type: ds18b20
        hub: default
        name: temp_tank_top
        slave: 5
        unit_of_measurement: "°C"
    platform: modified_modbus
  - holdings:
      - OwId: 28a8b2f30100007d
        device_class: temperature
        holdings_type: ds18b20
        hub: default
        name: temp_boiler
        slave: 5
        unit_of_measurement: "°C"
    platform: modified_modbus

switch 5:
  - holdings:
      - command_off: 7
        command_on: 263
        hub: default
        name: switch_5_7_pump_floor_circle
        offset: 29
        slave: 5
        state_off: 7
        state_on: 263
    platform: modified_modbus
  - holdings:
      - command_off: 8
        command_on: 264
        hub: default
        name: switch_5_8_pump_radiator_circle
        offset: 30
        slave: 5
        state_off: 8
        state_on: 264
    platform: modified_modbus
  - holdings:
      - command_off: 9
        command_on: 265
        hub: default
        name: switch_5_9_pump_waterheater
        offset: 31
        slave: 5
        state_off: 9
        state_on: 265
    platform: modified_modbus
  - holdings:
      - command_off: 10
        command_on: 266
        hub: default
        name: switch_5_10_servo_open_floor_circle
        offset: 32
        slave: 5
        state_off: 10
        state_on: 266
    platform: modified_modbus
  - holdings:
      - command_off: 11
        command_on: 267
        hub: default
        name: switch_5_11_servo_close_floor_circle
        offset: 33
        slave: 5
        state_off: 11
        state_on: 267
    platform: modified_modbus
  - holdings:
      - command_off: 12
        command_on: 268
        hub: default
        name: switch_5_12_servo_open_radiator_circle
        offset: 34
        slave: 5
        state_off: 12
        state_on: 268
    platform: modified_modbus
  - holdings:
      - command_off: 13
        command_on: 269
        hub: default
        name: switch_5_13_servo_close_radiator_circle
        offset: 35
        slave: 5
        state_off: 13
        state_on: 269
    platform: modified_modbus
  - holdings:
      - command_off: 14
        command_on: 270
        hub: default
        name: switch_5_14_waterheater_mode
        offset: 36
        slave: 5
        state_off: 14
        state_on: 270
    platform: modified_modbus
  - holdings:
      - command_off: 15
        command_on: 271
        hub: default
        name: switch_5_15_servo_waterheater
        offset: 37
        slave: 5
        state_off: 15
        state_on: 271
    platform: modified_modbus

binary_sensor 6:
  - holdings:
      - hub: default
        name: binary_sensor_6_1
        offset: 23
        slave: 6
        value_off: 513
        value_on: 769
        bit: 8
    platform: modified_modbus
  - holdings:
      - hub: default
        name: binary_sensor_6_2
        offset: 24
        slave: 6
        value_off: 1538
        value_on: 1794
        bit: 8
    platform: modified_modbus
  - holdings:
      - hub: default
        name: binary_sensor_wc
        offset: 25
        slave: 6
        value_off: 1539
        value_on: 1795
        bit: 8
    platform: modified_modbus
sensor  6:
  - holdings:
      - OwId: 28f69f0a060000cc
        holdings_type: ds18b20
        device_class: temperature
        hub: default
        name: temp_wc
        slave: 6
        unit_of_measurement: "°C"
    platform: modified_modbus
  - holdings:
      - holdings_type: hex
        hub: default
        name: test_string
        slave: 6
        unit_of_measurement: ""
        offset: 0
        count: 4
    platform: modified_modbus

switch 6:
  - holdings:
      - command_off: 4
        command_on: 260
        hub: default
        name: switch_wc
        offset: 26
        slave: 6
        state_off: 4
        state_on: 260
    platform: modified_modbus

binary_sensor 7:
  - holdings:
      - bit: 8
        hub: default
        name: binary_sensor_7_1
        offset: 23
        slave: 7
        value_off: 0
        value_on: 1
    platform: modified_modbus
  - holdings:
      - bit: 8
        hub: default
        name: binary_sensor_7_2
        offset: 24
        slave: 7
        value_off: 0
        value_on: 1
    platform: modified_modbus
  - holdings:
      - bit: 8
        hub: default
        name: binary_sensor_7_3
        offset: 25
        slave: 7
        value_off: 0
        value_on: 1
    platform: modified_modbus
  - holdings:
      - bit: 8
        hub: default
        name: binary_sensor_7_4
        offset: 26
        slave: 7
        value_off: 0
        value_on: 1
    platform: modified_modbus
  - holdings:
      - bit: 8
        hub: default
        name: binary_sensor_7_5
        offset: 27
        slave: 7
        value_off: 0
        value_on: 1
    platform: modified_modbus
  - holdings:
      - bit: 8
        hub: default
        name: binary_sensor_7_6
        offset: 28
        slave: 7
        value_off: 0
        value_on: 1
    platform: modified_modbus
switch 7:
  - holdings:
      - command_off: 7
        command_on: 263
        hub: default
        name: switch_7_7
        offset: 29
        slave: 7
        state_off: 7
        state_on: 263
    platform: modified_modbus
  - holdings:
      - command_off: 8
        command_on: 264
        hub: default
        name: switch_7_8
        offset: 30
        slave: 7
        state_off: 8
        state_on: 264
    platform: modified_modbus
  - holdings:
      - command_off: 9
        command_on: 265
        hub: default
        name: switch_7_9
        offset: 31
        slave: 7
        state_off: 9
        state_on: 265
    platform: modified_modbus
  - holdings:
      - command_off: 10
        command_on: 266
        hub: default
        name: switch_7_10
        offset: 32
        slave: 7
        state_off: 10
        state_on: 266
    platform: modified_modbus
  - holdings:
      - command_off: 11
        command_on: 267
        hub: default
        name: switch_7_11
        offset: 33
        slave: 7
        state_off: 11
        state_on: 267
    platform: modified_modbus
  - holdings:
      - command_off: 12
        command_on: 268
        hub: default
        name: switch_7_12
        offset: 34
        slave: 7
        state_off: 12
        state_on: 268
    platform: modified_modbus
  - holdings:
      - command_off: 13
        command_on: 269
        hub: default
        name: switch_7_13
        offset: 35
        slave: 7
        state_off: 13
        state_on: 269
    platform: modified_modbus
  - holdings:
      - command_off: 14
        command_on: 270
        hub: default
        name: switch_7_14
        offset: 36
        slave: 7
        state_off: 14
        state_on: 270
    platform: modified_modbus
  - holdings:
      - command_off: 15
        command_on: 271
        hub: default
        name: switch_7_15
        offset: 37
        slave: 7
        state_off: 15
        state_on: 271
    platform: modified_modbus
