- id: '1600279936586'
  alias: Turn on switch
  description: ''
  trigger:
  - entity_id: binary_sensor.binary_sensor4_2
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: switch.myswitch
    service: switch.toggle
  - data: {}
    entity_id: timer.test
    service: timer.start
  mode: single
